POST http://localhost:3000/productivity/budget/newCategory
Content-Type: application/json

{
  "categoryName": "Car"
}

###
GET http://localhost:3000/productivity/budget/categories
Accept: application/json